version: "3"

services:
  keycloack:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 8088:8080
    volumes:
      - ./insea-connect-auth-server/keycloak/import:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
    depends_on:
      - postgres
    command: start-dev --import-realm
    networks:
      - backend

  postgres:
    image: postgres:15.5-alpine3.19
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - 5435:5432
    networks:
      - backend

  flask-app:
    build:
      context: ./insea-connect-chatbot
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./insea-connect-chatbot:/app
    networks:
      - backend
    depends_on:
      - postgres

networks:
  backend:
    driver: bridge
